# https://docs.aws.amazon.com/codedeploy/latest/userguide/reference-appspec-file.html#appspec-reference-server
version: 0.0
os: linux
# https://docs.aws.amazon.com/codedeploy/latest/userguide/reference-appspec-file-structure-files.html
files:
 - source: source-file-location
   destination: destination-file-location
# https://docs.aws.amazon.com/codedeploy/latest/userguide/reference-appspec-file-structure-permissions.html
#permissions:
#  - object: object-specification
#    pattern: pattern-specification
#    except: exception-specification
#    owner: owner-account-name
#    group: group-name
#    mode: mode-specification
#    acls: 
#      - acls-specification 
#    context:
#      user: user-specification
#      type: type-specification
#      range: range-specification
#    type:
#      - object-type
# https://docs.aws.amazon.com/codedeploy/latest/userguide/reference-appspec-file-structure-hooks.html#appspec-hooks-server
#hooks:
#  deployment-lifecycle-event-name:
#    - location: script-location
#      timeout: timeout-in-seconds
#      runas: user-name
#    - location: script-location
#      timeout: timeout-in-seconds
#      runas: user-name
#  deployment-lifecycle-event-name2:
#    - location: script-location
#      timeout: timeout-in-seconds
#      runas: user-name